# Change prefix key to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Some basic options
set -g mouse on
setw -g mode-keys vi
set-option -g extended-keys on
set-option -g default-shell /bin/zsh

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# A set of options that should be acceptable
set -g @plugin 'tmux-plugins/tmux-sensible'

# Colorscheme
set -g @plugin 'uhs-robert/tmux-oasis'
set -g @oasis_flavor "starlight"

# Start plugin manager
run -b '~/.tmux/plugins/tpm/tpm'

